MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 40
DATASETS:
  DATASET_RATIO: [1.0, 1.5]
  # TRAIN: ("ytvis_2019_train")
  TRAIN: ("coco2ytvis2019_train", "ytvis_2019_train")
  TEST: ("ytvis_2019_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  STEPS: (12000, 24000)
  MAX_ITER: 32000
  # STEPS: (6000, 12000)
  # MAX_ITER: 16000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 20
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  SAMPLING_FRAME_RANGE: 20
  SAMPLING_FRAME_NUM: 16
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  RANDOM_FLIP: "flip_by_clip"
  AUGMENTATIONS: [ ]
  MIN_SIZE_TRAIN: (224, 224)
  # MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
  # MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 224
  CROP:
    ENABLED: True
    CLIP_FRAME_CNT: 16
    TYPE: "absolute_range"
    SIZE: (224, 224)
  PSEUDO:
    AUGMENTATIONS: [ 'rotation' ]
    MIN_SIZE_TRAIN: (224, 224)
    # MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
    # MAX_SIZE_TRAIN: 768
    CROP:
      ENABLED: True
      TYPE: "absolute_range"
      SIZE: (224, 224)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 2000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 8
VERSION: 2
